name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Build and push Docker image to Hugging Face
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          docker build -t $HF_USERNAME/$SPACE_NAME .
          docker tag $HF_USERNAME/$SPACE_NAME:latest $HF_USERNAME/$SPACE_NAME:$(date +%Y%m%d%H%M%S)
          echo $HF_TOKEN | docker login --username $HF_USERNAME --password-stdin huggingface.co
          docker push huggingface.co/$HF_USERNAME/$SPACE_NAME:latest
          docker push huggingface.co/$HF_USERNAME/$SPACE_NAME:$(date +%Y%m%d%H%M%S)
